# Generated by Django 3.1.2 on 2020-10-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('x_coordinates', models.IntegerField()),
                ('y_coordinates', models.IntegerField()),
                ('from_date', models.DateField()),
                ('till_date', models.DateField()),
                ('location_category', models.CharField(choices=[('R', 'Residence'), ('W', 'Workplace'), ('V', 'Visit')], default='R', max_length=1)),
            ],
        ),
    ]
